# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.141.59-radium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCE: 10

  hub:
    image: selenium/hub:3.141.59-radium
    container_name: dockerhub
    hostname: dockerhub
    ports:
      - "4445:4444"