version: '3.3'

services:
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-radium
    ports:
      - '4445:4444'
      - '5901:5900'
    volumes:
      - /dev/shm:/dev/shm
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - selenium